name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Java and Android SDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Cordova
        run: npm install -g cordova

      # चरण 1: केवल एंड्रॉइड प्लेटफॉर्म जोड़ें
      - name: Add Android Platform
        run: cordova platform add android@12.0.1

      # चरण 2: प्लगइन्स इंस्टॉल करें और हुक चलाएं (यह सबसे महत्वपूर्ण चरण है)
      - name: Prepare Android Platform (Installs plugins and runs hooks)
        run: cordova prepare android

      # चरण 3: आवश्यक बिल्ड-टूल्स इंस्टॉल करें (सुरक्षित रहने के लिए)
      - name: Install required Android Build Tools
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2"

      # चरण 4: अब APK बनाएं
      - name: Build Android Debug APK
        run: cordova build android

      # चरण 5: APK अपलोड करें
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VoiceCMD-debug-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
