name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Cordova and dependencies
        run: |
          npm install -g cordova
          npm install

      - name: Add Android Platform (Fixed Version)
        run: cordova platform add android@12.0.1

      - name: Install Android Build Tools
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2"

      # --- बिल्ड कमांड को सरल किया गया है (डीबग APK के लिए) ---
      - name: Build Android Debug APK
        run: cordova build android

      # --- APK का सही रास्ता (डीबग वाला) ---
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VoiceCMD-debug-apk
          # यह वही रास्ता है जो आपने बताया
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
          
