name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Cordova and dependencies
        run: |
          npm install -g cordova
          npm install

      - name: Add Android Platform
        run: cordova platform add android@latest

      - name: Build Android APK
        run: cordova build android --release -- -- --packageType=apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: VoiceCMD-apk
          path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
